import type { Metadata } from "next";
import { ABeeZee } from "next/font/google";
import "./globals.css";


const abeezee = ABeeZee({
  variable: "--font-abeezee",
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Digital Hup Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${abeezee.variable} antialiased`}>{children}</body>
    </html>
  );
}
